spring:
  data:
    mongodb:
      # connection uri supplied by ENV variable if deployed via docker compose, default to localhost for running in IDE
      uri: ${DB_URI:mongodb://localhost:27017/db}
      auto-index-creation: true
service:
  max-retries: 5
sequence-mapping:
  alphabet: 'abcdefghijklmnopqrstuvwxyz0123456789'